"""verificação de tabelas e colunas

Revision ID: d73520a17a53
Revises: 
Create Date: 2024-09-15 12:13:49.585870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd73520a17a53'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('filmes', 'Nome',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('filmes', 'Genero',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('filmes', 'Ano',
               existing_type=mysql.YEAR(),
               type_=sa.Integer(),
               nullable=True)
    op.alter_column('filmes', 'Sinopse',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('filmes', 'Diretor',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_index('id_UNIQUE', table_name='filmes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('id_UNIQUE', 'filmes', ['id'], unique=True)
    op.alter_column('filmes', 'Diretor',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('filmes', 'Sinopse',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('filmes', 'Ano',
               existing_type=sa.Integer(),
               type_=mysql.YEAR(),
               nullable=False)
    op.alter_column('filmes', 'Genero',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('filmes', 'Nome',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
